[package]
name = "Move2Example"
version = "1.0.0"
authors = []

[addresses]
example = "_"

[dev-addresses]
example = "0xd18f7966ba8bcb137b04374aaacb42750659969a48ad6f32bf89e35bec0ee662"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
